# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_game_development # アプリケーション名_development など、わかりやすい名前に変更
  username: postgres # PostgreSQLのユーザー名 (例: postgres)
  password: test # PostgreSQLのパスワード
  host: localhost # PostgreSQLが動作しているホスト (通常はlocalhost)
  port: 5432 # PostgreSQLのデフォルトポート

test:
  <<: *default
  database: rails_game_test
  username: postgres
  password: test
  host: localhost
  port: 5432

production:
  <<: *default
  database: rails_game_production
  username: <%= ENV['POSTGRES_USERNAME'] %> # 環境変数を使うのが一般的
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>